# Generated by Django 3.2.4 on 2022-02-05 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0002_auto_20210807_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.collection')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size')),
            ],
        ),
        migrations.CreateModel(
            name='CollectionSizePrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('collectionSize', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.collectionsize')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('prices', models.ManyToManyField(through='pricing.CollectionSizePrice', to='pricing.CollectionSize')),
            ],
        ),
        migrations.CreateModel(
            name='PricingItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(default=0)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.collection')),
                ('pricing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricing')),
                ('size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.size')),
            ],
        ),
        migrations.AddField(
            model_name='collectionsizeprice',
            name='pricing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pricing.pricing'),
        ),
    ]
