# Generated by Django 3.2.4 on 2022-02-05 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricing', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pricing',
            new_name='PricingPackage',
        ),
    ]
