# Generated by Django 3.2.4 on 2021-07-28 05:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=30)),
                ('ordered_date', models.DateField(blank=True)),
                ('arrival_date', models.DateField(blank=True)),
                ('available', models.BooleanField(default=False)),
                ('packing_sheet', models.FileField(blank=True, upload_to='shipments/')),
            ],
        ),
        migrations.CreateModel(
            name='ShipmentItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(blank=True, max_length=30)),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='brand',
            name='name',
            field=models.CharField(max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='brand',
            name='website',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pile_count',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='pile_length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='color',
            name='texture_color',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddConstraint(
            model_name='carpet',
            constraint=models.UniqueConstraint(fields=('design', 'color', 'size'), name='unique_ein'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('primary_color', 'texture_color'), name='unique_color'),
        ),
        migrations.AddConstraint(
            model_name='size',
            constraint=models.UniqueConstraint(fields=('length', 'width', 'shape'), name='unique_size'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='carpet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.carpet'),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carpets.shipment'),
        ),
    ]
