# Generated by Django 3.2.4 on 2021-07-16 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0002_auto_20210716_2238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipment',
            name='ordered_items',
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='shipment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='carpets.shipment'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='arrival_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='ordered_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='shipmentitem',
            name='barcode',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
