# Generated by Django 3.2.4 on 2021-07-17 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0003_auto_20210716_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='packing_sheet',
            field=models.FileField(blank=True, upload_to='shipments/'),
        ),
    ]
