# Generated by Django 3.2.4 on 2021-07-21 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0004_shipment_packing_sheet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='carpet',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='shipment',
        ),
        migrations.AlterField(
            model_name='size',
            name='shape',
            field=models.CharField(choices=[('Rectangle', 'Rectangle'), ('Oval', 'Oval'), ('Round', 'Round')], default='Rectangle', max_length=20),
        ),
        migrations.DeleteModel(
            name='Shipment',
        ),
        migrations.DeleteModel(
            name='ShipmentItem',
        ),
    ]
