# Generated by Django 3.2.4 on 2021-07-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0006_envcolor_floortexture_floortype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='floortexture',
            old_name='type',
            new_name='floortype',
        ),
    ]
