# Generated by Django 3.2.4 on 2021-08-03 01:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0002_auto_20210728_0527'),
        ('carpets', '0007_rename_type_floortexture_floortype'),
    ]

    operations = [
    ]
