# Generated by Django 3.2.4 on 2021-08-04 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carpets', '0008_merge_20210802_2007'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EnvColor',
        ),
        migrations.DeleteModel(
            name='FloorTexture',
        ),
        migrations.DeleteModel(
            name='FloorType',
        ),
    ]
