# Generated by Django 3.2.4 on 2021-08-04 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_designincolor_image_file'),
        ('shipment', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='carpet',
        ),
        migrations.RemoveField(
            model_name='shipmentitem',
            name='id',
        ),
        migrations.AddField(
            model_name='shipment',
            name='processed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='carpet_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='catalog.carpet'),
            preserve_default=False,
        ),
    ]
