# Generated by Django 3.2.4 on 2021-08-05 06:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210805_0607'),
        ('shipment', '0002_auto_20210804_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shipmentitem',
            name='carpet_ptr',
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='carpet',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='catalog.carpet'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shipmentitem',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
