# Generated by Django 3.2.4 on 2022-04-25 05:56

from django.db import migrations, models
import django.db.models.deletion
import rugviz.models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210807_0052'),
        ('rugviz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarpetPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=rugviz.models.carpet_picture_path)),
                ('carpet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='catalog.carpet')),
            ],
        ),
    ]
