# Generated by Django 3.2.4 on 2021-11-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_consumer'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='retailer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
    ]
