# Generated by Django 3.2.3 on 2021-06-01 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Design',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Carpet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(max_length=30)),
                ('pattern', models.IntegerField()),
                ('name', models.CharField(max_length=50)),
                ('image_file', models.FileField(null=True, upload_to='carpets/')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('width', models.DecimalField(decimal_places=2, max_digits=5)),
                ('thread_count', models.IntegerField()),
                ('thread_length', models.DecimalField(decimal_places=2, max_digits=5)),
                ('inventory', models.IntegerField(default=0)),
                ('design', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carpets.design')),
            ],
        ),
    ]
