# Generated by Django 3.2.4 on 2021-08-02 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carpet',
            name='image_file',
            field=models.ImageField(null=True, upload_to='catalog/DesignColorSize'),
        ),
        migrations.AlterField(
            model_name='designincolor',
            name='image_file',
            field=models.ImageField(null=True, upload_to='catalog/DesignColor'),
        ),
    ]
