# Generated by Django 3.2.4 on 2021-08-07 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='primary_color',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='color',
            name='texture_color',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
