# Generated by Django 3.2.4 on 2021-08-04 22:50

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20210802_1828'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designincolor',
            name='image_file',
            field=models.ImageField(blank=True, null=True, upload_to=catalog.models.design_image_path),
        ),
    ]
