# Generated by Django 3.2.4 on 2021-08-05 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_designincolor_image_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='length',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='size',
            name='width',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
