# Generated by Django 3.2.4 on 2021-08-05 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_auto_20210805_0639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='shape',
            field=models.CharField(choices=[('D', 'Rectangle'), ('R', 'Runner'), ('C', 'Round')], default='D', max_length=20),
        ),
    ]
